# Übungsaufgaben 3
## 1 Lineare Regression & Qualitative Variablen

### 1. Gehaltsunterschied Männer / Frauen

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
salaries = pd.read_csv('salaries.csv')
salaries.head()

rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750
3      Prof          B             45           39  Male  115000
4      Prof          B             40           41  Male  141500

In [3]:
# linear regression model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [4]:
# features is only sex
X = salaries.copy()['sex'].values.reshape(-1,1)
y = salaries.copy()['salary'].values.reshape(-1,1)

# features are 'male' or 'female'
# should transform to numeric values
male = 0
female = 1
for i, sex in enumerate(X):
    X[i] = male if sex == 'Male' else female

X.shape, y.shape

((397, 1), (397, 1))

In [5]:
# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train, y_train

(array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],

In [6]:
reg = LinearRegression().fit(X_train, y_train)

print('a0 (mens average salary):', reg.intercept_[0])
print('a1 (women salary difference):', reg.coef_[0][0])

a0 (mens average salary): 116311.41403508771
a1 (women salary difference): -16708.63278508772


Der Intercept stellt den durschschnittlichen Gehalt der Männer da (feature ist 0). a1 stellt die Differenz im Gehalt dar. Frauen verdienen dementsprechend weniger.

### 2. Lineare Regression mit allen Variablen

In [7]:
salaries.head()

rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750
3      Prof          B             45           39  Male  115000
4      Prof          B             40           41  Male  141500

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
X = salaries.drop(['salary'], axis=1)
y = salaries['salary'].values.reshape(-1,1)
X.loc[0]

rank             Prof
discipline          B
yrs.since.phd      19
yrs.service        18
sex              Male
Name: 0, dtype: object

In [10]:
# transform to numeric values: rank, discipline, sex
enc = OneHotEncoder(drop='first')
enc.fit(X)
enc.categories_

[array(['AssocProf', 'AsstProf', 'Prof'], dtype=object),
 array(['A', 'B'], dtype=object),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52,
        54, 56]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 43, 44, 45, 46, 48, 49, 51, 53, 57,
        60]),
 array(['Female', 'Male'], dtype=object)]

In [11]:
X = enc.transform(X).toarray()

In [12]:
reg = LinearRegression().fit(X, y)

In [13]:
error = np.mean((reg.predict(X) - y)**2)
error

311152519.2542734

Ergebnisse

In [14]:
# interpret coefficients
print('a0 (womans assoc. prof discipline A average salary):', reg.intercept_[0])

for i, col in enumerate(enc.categories_):
    # exclude numeric values
    if all(isinstance(x, np.int64) for x in col):
        continue
    
    for j in range(1, len(col)):
        print('a{} ({}): {}'.format(i+j, col[j], reg.coef_[0][i+j-1]))

a0 (womans assoc. prof discipline A average salary): 84930.27093828715
a1 (AsstProf): -20054.76287632027
a2 (Prof): 27668.379380799284
a2 (B): 27668.379380799284
a5 (Male): 3963.999041055815
